/* Generated by pico.express. Browser clients are not a security boundary. */
(function () {
  "use strict";
  var loader = document.currentScript;
  if (!loader) return;
  var clientId = loader.dataset.picoClientId;
  var configUrl = loader.dataset.picoConfigUrl;
  var entry = loader.dataset.picoEntry;
  var storageKey = "pico.express:browser-config:" + clientId;
  var runtimeKey = Symbol.for("pico.express.browser.runtime.v1");
  var currentRevision = -1;
  var installedBehavior = null;
  var latestAcceptedRevision = -1;
  var latestAcceptedBehavior = null;
  var entryLoaded = false;
  var reloadPending = false;
  function valid(configuration, allowStale) {
    if (!configuration || configuration.schemaVersion !== "1.0" || configuration.clientId !== clientId ||
        typeof configuration.applicationId !== "string" ||
        !Number.isSafeInteger(configuration.policyRevision) || configuration.policyRevision < 0 ||
        !Array.isArray(configuration.enabledPatchKeys) ||
        !configuration.enabledPatchKeys.every(function (key) { return typeof key === "string"; })) return false;
    if (!allowStale) return true;
    var observed = Date.parse(configuration.evaluatedAtUtc);
    var age = Date.now() - observed;
    var maximumAge = Math.min(86400, Math.max(0, Number(configuration.cache && configuration.cache.staleIfErrorSeconds) || 0)) * 1000;
    return Number.isFinite(observed) && age >= -300000 && age <= maximumAge;
  }
  function install(configuration) {
    if (!valid(configuration, false) || configuration.policyRevision < currentRevision) return false;
    var enabled = new Set(Array.isArray(configuration.enabledPatchKeys) ? configuration.enabledPatchKeys : []);
    Object.defineProperty(globalThis, runtimeKey, {
      configurable: true,
      value: Object.freeze({
        applicationId: configuration.applicationId,
        policyRevision: configuration.policyRevision,
        enabled: function (sourceOid, unitId) {
          return enabled.has("git:" + "application_df90639e-af97-4c5e-8ef9-3c7592dabdc6" + ":" + sourceOid + ":" + unitId);
        }
      })
    });
    currentRevision = configuration.policyRevision;
    installedBehavior = behavior(configuration);
    latestAcceptedRevision = configuration.policyRevision;
    latestAcceptedBehavior = installedBehavior;
    return true;
  }
  function behavior(configuration) {
    var prefix = "git:" + "application_df90639e-af97-4c5e-8ef9-3c7592dabdc6" + ":";
    return JSON.stringify(configuration.enabledPatchKeys.filter(function (key) {
      return key.startsWith(prefix);
    }).slice().sort());
  }
  function persist(configuration) {
    var serialized = JSON.stringify(configuration);
    try {
      localStorage.setItem(storageKey, serialized);
      return localStorage.getItem(storageKey) === serialized;
    } catch (_) {
      return false;
    }
  }
  function acceptFresh(configuration) {
    if (!valid(configuration, false) || configuration.policyRevision < latestAcceptedRevision) return false;
    var nextBehavior = behavior(configuration);
    if (configuration.policyRevision === latestAcceptedRevision && latestAcceptedBehavior !== null && nextBehavior !== latestAcceptedBehavior) return false;
    if (reloadPending && configuration.policyRevision === latestAcceptedRevision && nextBehavior === latestAcceptedBehavior) return true;
    if (entryLoaded && installedBehavior !== null && nextBehavior !== installedBehavior) {
      if (!persist(configuration)) {
        console.warn("pico.express could not persist changed JavaScript activations for reload");
        return false;
      }
      latestAcceptedRevision = configuration.policyRevision;
      latestAcceptedBehavior = nextBehavior;
      reloadPending = true;
      if (window.location && typeof window.location.reload === "function") {
        window.location.reload();
      } else {
        console.warn("pico.express requires a page reload to apply changed JavaScript activations");
      }
      return true;
    }
    if (!install(configuration)) return false;
    persist(configuration);
    return true;
  }
  function loadEntry() {
    var script = document.createElement("script");
    script.src = new URL(entry, document.baseURI).href;
    script.async = false;
    script.addEventListener("load", function () {
      window.dispatchEvent(new CustomEvent("pico.express:ready"));
    }, { once: true });
    entryLoaded = true;
    document.head.appendChild(script);
  }
  function fetchConfiguration() {
    var requestUrl = new URL(configUrl, document.baseURI);
    requestUrl.searchParams.set("clientId", clientId);
    return fetch(requestUrl.href, {
      credentials: "omit",
      headers: { "accept": "application/json" }
    }).then(function (response) {
      if (!response.ok) throw new Error("pico.express browser config returned " + response.status);
      return response.json();
    }).then(function (configuration) {
      if (!valid(configuration, false)) throw new Error("pico.express browser config is invalid");
      return configuration;
    });
  }
  var cached = null;
  try { cached = JSON.parse(localStorage.getItem(storageKey)); } catch (_) { cached = null; }
  if (valid(cached, true)) {
    install(cached);
    loadEntry();
    fetchConfiguration().then(acceptFresh).catch(function (error) { console.warn(error); });
  } else {
    fetchConfiguration().then(function (configuration) {
      acceptFresh(configuration);
      loadEntry();
    }).catch(function (error) {
      console.error("pico.express could not initialize", error);
    });
  }
  window.setInterval(function () {
    fetchConfiguration().then(acceptFresh).catch(function (error) { console.warn(error); });
  }, 15000);
})();
